/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './views/__root'
import { Route as SobreRouteImport } from './views/sobre'
import { Route as AuthRouteImport } from './views/_auth'
import { Route as AppRouteImport } from './views/_app'
import { Route as IndexRouteImport } from './views/index'
import { Route as AuthRegisterRouteImport } from './views/_auth/register'
import { Route as AuthLoginRouteImport } from './views/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './views/_auth/forgot-password'
import { Route as AppProfileRouteImport } from './views/_app/profile'
import { Route as AppDashboardIndexRouteImport } from './views/_app/dashboard/index'
import { Route as AppCursoIdRouteImport } from './views/_app/curso/$id'
import { Route as AppCursoDisciplinaIdRouteImport } from './views/_app/curso/disciplina/$id'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppRoute,
} as any)
const AppCursoIdRoute = AppCursoIdRouteImport.update({
  id: '/curso/$id',
  path: '/curso/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCursoDisciplinaIdRoute = AppCursoDisciplinaIdRouteImport.update({
  id: '/curso/disciplina/$id',
  path: '/curso/disciplina/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sobre': typeof SobreRoute
  '/profile': typeof AppProfileRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/curso/$id': typeof AppCursoIdRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/curso/disciplina/$id': typeof AppCursoDisciplinaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sobre': typeof SobreRoute
  '/profile': typeof AppProfileRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/curso/$id': typeof AppCursoIdRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/curso/disciplina/$id': typeof AppCursoDisciplinaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/sobre': typeof SobreRoute
  '/_app/profile': typeof AppProfileRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_app/curso/$id': typeof AppCursoIdRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
  '/_app/curso/disciplina/$id': typeof AppCursoDisciplinaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sobre'
    | '/profile'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/curso/$id'
    | '/dashboard'
    | '/curso/disciplina/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sobre'
    | '/profile'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/curso/$id'
    | '/dashboard'
    | '/curso/disciplina/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/sobre'
    | '/_app/profile'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_app/curso/$id'
    | '/_app/dashboard/'
    | '/_app/curso/disciplina/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/curso/$id': {
      id: '/_app/curso/$id'
      path: '/curso/$id'
      fullPath: '/curso/$id'
      preLoaderRoute: typeof AppCursoIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/curso/disciplina/$id': {
      id: '/_app/curso/disciplina/$id'
      path: '/curso/disciplina/$id'
      fullPath: '/curso/disciplina/$id'
      preLoaderRoute: typeof AppCursoDisciplinaIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppProfileRoute: typeof AppProfileRoute
  AppCursoIdRoute: typeof AppCursoIdRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppCursoDisciplinaIdRoute: typeof AppCursoDisciplinaIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppProfileRoute: AppProfileRoute,
  AppCursoIdRoute: AppCursoIdRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppCursoDisciplinaIdRoute: AppCursoDisciplinaIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
